[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "export PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1",
  "npm install",
  "npx prisma generate",
  "npx prisma db push",
  "npm run build"
]

[start]
cmd = "npm start"

